@startuml 演習6-3
'left to right direction
[*] -right-> メニュー画面
メニュー画面 --> 予約と確認画面
予約と確認画面 --> メニュー画面
予約と確認画面 -right-> あなたの順番
予約と確認画面 -right-> あなたの順番
あなたの順番 --> メニュー画面
メニュー画面 --> 今の順番 
今の順番 --> メニュー画面 
メニュー画面 -right-> [*]
@enduml