@startuml 演習6-5-1
class ライトトレーサー{}
class 光センサー{}
class 右モータ{}
class 左モータ{}
class CPU{}
class 電源SW{}

ライトトレーサー "1"--"1" 光センサー
ライトトレーサー "1"--"1" 右モータ
ライトトレーサー "1"--"1" 左モータ
ライトトレーサー "1"--"1" CPU
ライトトレーサー "1"--"1" 電源SW
@enduml