@startuml 演習7-3
|顧客|
|給士|
|料理人|

|顧客|
:案内を依頼する;
|給士|
:テーブルに案内する;
:メニューを渡す;
:メニュー]
|顧客|
:注文を決める;
:注文]
:メニュー]
|給士|
fork
    :注文を受ける;
    :伝票を書く;
    :料理人に注文を伝える;
fork again
    |料理人|
    :注文を受ける;
    :料理を作る;
    :料理]
end fork
|給士|
:料理を運ぶ;
:伝票を渡す;
:料理]
:伝票]
|顧客|
:料理を食べる;
:代金を払う;
::伝票;
stop
@enduml